name: Slack smoke

on:
  workflow_dispatch: {}

jobs:
  slack-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install slack_sdk only
        run: |
          python -m pip install --upgrade pip
          pip install slack_sdk==3.36.0
      - name: Send Slack smoke message
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        run: |
          python src/slack_smoke.py


